planets/urls.py
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('records/', include('records.urls', namespace='records')),
    path('api/', include('records.api.urls', namespace='api'))
]

records/api/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('records/', views.RecordListView.as_view(), name='records_list'),
    path('records/add/', views.RecordCreateView.as_view(), name='record_add'),
    path('records/<name>/', views.RecordDetailView.as_view(), name='record_detail'),
    path('records/<name>/update/', views.RecordUpdateView.as_view(), name='record_update'),
    path('records/<name>/delete/', views.RecordDeleteView.as_view(), name='record_delete'),
    
]

records/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('', views.RecordListView.as_view(), name='record_list'),
    path('add/', views.RecordFormView.as_view(), name='record_add'),
    path('<name>/', views.RecordDetailView.as_view(), name='record_detail'),
    path('<name>/update/', views.RecordUpdateView.as_view(), name='record_update'),
    path('<name>/delete/', views.record_delete, name='record_delete'),

]

records/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Planet(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    ordinality = models.IntegerField(unique=True)
    size = models.FloatField()
    distance = models.FloatField()

    def get_absolute_url(self):
        return reverse("records:record_detail", kwargs={'name': self.name})
    
    class Meta: 
        ordering = ('ordinality',)
    
# this func is the default human redable representation of the object
    def __str__(self):
        return self.name

records/forms.py
from .models import Planet
from django import forms

class PlanetForm(forms.ModelForm):    
    class Meta:
        model = Planet
        fields = ("name", "ordinality", "description", "size", "distance")

records/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from ..models import Planet
from .serializers import RecordSerializer

# curl -X POST -d '{"name":"Earth","description":"Hottest Planet","ordinality":3,"size":1.0,"distance":4.5}' 
# -H 'Content-Type: application/json' http://127.0.0.1:8000/api/records/add/
class RecordCreateView(generics.CreateAPIView):
    serializer_class = RecordSerializer

# curl -X DELETE http://127.0.0.1:8000/api/records/Earth/delete/
class RecordDeleteView(generics.DestroyAPIView):
    queryset = Planet.objects.all() #optimize this later
    serializer_class = RecordSerializer
    lookup_field = 'name'

# curl -X PUT -d '{"name":"Earth","description":"Hottest Planet","ordinality":3,"size":1.0,"distance":4.5}' 
# -H 'Content-Type: application/json' http://127.0.0.1:8000/api/records/<name>/update/
class RecordUpdateView(generics.UpdateAPIView):
    queryset = Planet.objects.all()
    serializer_class = RecordSerializer
    lookup_field = 'name'

# curl http://127.0.0.1:8000/api/records/Mercury/ # requests Mercury Planet
# curl http://127.0.0.1:8000/api/records/ | json_pp # formats JSON
class RecordListView(generics.ListAPIView):
    queryset = Planet.objects.all()
    serializer_class = RecordSerializer

class RecordDetailView(generics.RetrieveAPIView):
    queryset = Planet.objects.all()
    serializer_class = RecordSerializer
    lookup_field = 'name'

# queryset: The base QuerySet to use to retrieve objects
# serializer_class: The class to serialize objects

# {"name":"Mercury","description":"Hottest Planet","ordinality":1,"size":1.0,"distance":4.5}

records/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls.base import get_script_prefix
from records.forms import PlanetForm
from .models import Planet
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.urls import reverse

# Create your views here.

class RecordListView(ListView):
    queryset = Planet.objects.all()
    context_object_name = 'planet_records'
    template_name = 'list.html'

class RecordDetailView(DetailView): 
    model = Planet
    context_object_name = 'planet'
    template_name = 'detail.html'

    def get_object(self, queryset=None):
        slug = self.kwargs['name']
        planet = get_object_or_404(Planet, name=slug)

        return planet

class RecordUpdateView(UpdateView):
    model = Planet
    fields = ['name', 'ordinality', 'description', 'size', 'distance']
    template_name = "update.html"
    success_url = "/records/"

    def get_object(self, queryset=None):
        slug = self.kwargs['name']
        planet = get_object_or_404(Planet, name=slug)

        return planet
    
class RecordFormView(FormView):
    form_class = PlanetForm
    template_name = "add.html"
    success_url = "/records/"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

def record_delete(request, name):
    planet = get_object_or_404(Planet, name = name)
    planet.delete()

    return HttpResponseRedirect(reverse('records:record_list'))

    

records/templates/add.html
{% extends 'base.html' %}
{% block title %}Add a Planet{% endblock %}

{% block content %}
<h1>Add a New Planet</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
{% endblock %}

records/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>



    

records/templates/detail.html
{% extends 'base.html' %}
{% block title %}{{ planet.name }}{% endblock %}

{% block content %}
    <h1>{{ planet.name }}</h1>
    <p>{{ planet.description }}</p>
    <br/>
    <p>
        Ordinality: {{ planet.ordinality }} <br/>
        Size: {{ planet.size }} Earth Masses<br/>
        Distance: {{ planet.distance }} AU<br/>
    </p>

    <form action="{% url "records:record_delete" planet.name %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete Planet" />
    </form>
{% endblock %}

records/templates/list.html
{% extends 'base.html' %}

{% block title %}Planets{% endblock %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
</style>

<table>
  <tr>
    <th>Ordinality</th>
    <th>Name</th>
    <th>Size</th>
    <th>Distance</th>
    <th></th>
  </tr>
    {% for record in planet_records %}
        <tr>
            <td>{{ record.ordinality }}</td>
            <td><a href="{{ record.get_absolute_url }}">{{ record.name }}</a></td>
            <td>{{ record.size }}</td>
            <td>{{ record.distance }}</td>
            <td>
              <form action="{% url "records:record_update" record.name %}">
                <input type="submit" value="Update" />
              </form>
            </td>
        </tr>
    {% endfor %}
</table>
<br/>

<form action="{% url "records:record_add" %}">
    <input type="submit" value="Add a Planet" />
</form>
{% endblock %}

records/templates/update.html
<form method="post"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <input type="submit" value="Save"> 
</form> 